### ISSUE TITLE
a link in your references is not working 

### ISSUE THREAD

**Issue by Asma-Hawari** [Chinmay26/Near-Duplicate-Video-Detection#3]
this link is invalid : 
NDVD using metric learning : https://github.com/Chinmay26/Near-Duplicate-Video-Detection/blob/master/openaccess.thecvf.com/content_ICCV_2017_workshops/papers/w5/Kordopatis-Zilos_Near-Duplicate_Video_Retrieval_ICCV_2017_paper.pdf

**Comment by Chinmay26** [comment]
Will fix this. This is the correct link.

http://openaccess.thecvf.com/content_ICCV_2017_workshops/w5/html/Kordopatis-Zilos_Near-Duplicate_Video_Retrieval_ICCV_2017_paper.html
